### ISSUE TITLE
Linux version requires newer Glibc than listed

### ISSUE THREAD

**Issue by jrugia** [00-Evan/shattered-pixel-dungeon#1608]
The Linux version says it requires glibc 2.17+  however when attempting to run the game with at least glibc 2.23 I get the below error:

`./Shattered\ Pixel\ Dungeon 
java.lang.UnsatisfiedLinkError: /tmp/lwjgljojo/3.3.1-765/liblwjgl.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.26' not found (required by /tmp/lwjgljojo/3.3.1-765/liblwjgl.so)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.load0(Unknown Source)
	at java.base/java.lang.System.load(Unknown Source)
	at org.lwjgl.system.Library.loadSystem(Library.java:179)
	at org.lwjgl.system.Library.loadSystemFromLibraryPath(Library.java:169)
	at org.lwjgl.system.Library.loadSystem(Library.java:124)
	at org.lwjgl.system.Library.loadSystem(Library.java:63)
	at org.lwjgl.system.Library.<clinit>(Library.java:51)
	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:100)
	at org.lwjgl.system.Pointer$Default.<clinit>(Pointer.java:67)
	at org.lwjgl.system.Callback.<clinit>(Callback.java:40)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:84)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3ApplicationConfiguration.getDisplayMode(Lwjgl3ApplicationConfiguration.java:219)
	at com.shatteredpixel.shatteredpixeldungeon.desktop.DesktopLauncher.main(DesktopLauncher.java:178)

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "main"
Failed to launch JVM`

I'm trying to run this on an old Debian 9 system, I understand it's quite an old distro these days but I'm not in a position to upgrade.  Would be greatly appreciated if the game could be compiled for older glibc.

**Comment by 00-Evan** [comment]
Hm, can you please check if prior versions of Shattered have the same error? That error is relating to a dependency which was last updated in v1.3.0

**Comment by jrugia** [comment]
Since no Linux version is available in 1.3.2 I downloaded the Jar file - same error is present.

Tried version 1.2.3 but gives error below:

`jojo@the-red-dream:~/Main$ java -jar ShatteredPD-v1.2.3-Desktop.jar 
[GAME] com.badlogic.gdx.utils.GdxRuntimeException: Error creating controller manager: com.badlogic.gdx.controllers.desktop.JamepadControllerManager
	at com.badlogic.gdx.controllers.Controllers.initialize(Controllers.java:119)
	at com.badlogic.gdx.controllers.Controllers.addListener(Controllers.java:65)
	at com.watabou.noosa.Game.create(Game.java:106)
	at com.shatteredpixel.shatteredpixeldungeon.ShatteredPixelDungeon.create(ShatteredPixelDungeon.java:149)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:433)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:381)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:143)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
	at com.shatteredpixel.shatteredpixeldungeon.desktop.DesktopLauncher.main(DesktopLauncher.java:178)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'libjamepad64.so' for target: Linux, 64-bit
	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:126)
	at com.studiohartman.jamepad.ControllerManager.<init>(ControllerManager.java:66)
	at com.badlogic.gdx.controllers.desktop.JamepadControllerManager.<init>(JamepadControllerManager.java:34)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at com.badlogic.gdx.utils.reflect.ClassReflection.newInstance(ClassReflection.java:93)
	at com.badlogic.gdx.controllers.Controllers.initialize(Controllers.java:117)
	... 8 more
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: java.lang.UnsatisfiedLinkError: /tmp/libgdxjojo/954b664e/libjamepad64.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /tmp/libgdxjojo/954b664e/libjamepad64.so)
	at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:322)
	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:122)
	... 17 more
Caused by: java.lang.UnsatisfiedLinkError: /tmp/libgdxjojo/954b664e/libjamepad64.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /tmp/libgdxjojo/954b664e/libjamepad64.so)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1088)
	at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:328)
	at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:297)
	... 18 more

sh: 5: Syntax error: Unterminated quoted string`

With version 1.1.2 (Jar file) runs fine though.

**Comment by 00-Evan** [comment]
From taking a quick look at lwjgl's changelog, it looks like the minimum glibc was bumped to 2.24 in lwjgl 3.3.0. Shattered was updated from lwjgl 3.2.3 to 3.3.3 in v1.3.0

Conveniently, the minimum was then lowered down to glibc 2.17 in lwjgl 3.3.2, and I am in the process of updating Shattered to use the latest lwjgl (3.3.3) in an upcoming patch.

**Comment by jrugia** [comment]
That sounds great news, thanks :)

**Comment by 00-Evan** [comment]
Here's a link to the current v2.3.1 linux build, please let me know if it works for you: https://drive.google.com/file/d/1afTV-yYQ4WMyAgY--KkkFgQMqfkxiUTl

**Comment by jrugia** [comment]
It runs fine now yes.

**Comment by 00-Evan** [comment]
Great! I've had to do some hacky stuff to get the library updates to work on Android 4.0-4.3, so I'm going to let it set in beta for a little while longer, but assuming no issues pop up then that exact build will be public here in a couple of days.
