### ISSUE TITLE
Viewing Ranking After Completion

### ISSUE THREAD

**Issue by teddytree** [00-Evan/shattered-pixel-dungeon#180]
GAME: @@ New badge: Happy end

When I tried to view my ranking after completing the game, I got an error message saying unable to load. When I restarted the game and viewed my ranking again, the error no longer appeared.

PD: JSONArray[0] not a string.
org.json.JSONException: JSONArray[0] not a string.
        at org.json.JSONArray.getString(JSONArray.java:333)
        at com.watabou.utils.Bundle.getClassArray(Bundle.java:201)
        at com.shatteredpixel.shatteredpixeldungeon.items.artifacts.UnstableSpellbook.restoreFromBundle(UnstableSpellbook.java:171)
        at com.watabou.utils.Bundle.get(Bundle.java:126)
        at com.watabou.utils.Bundle.get(Bundle.java:138)
        at com.shatteredpixel.shatteredpixeldungeon.actors.hero.Belongings.restoreFromBundle(Belongings.java:130)
        at com.shatteredpixel.shatteredpixeldungeon.actors.hero.Hero.restoreFromBundle(Hero.java:231)
        at com.watabou.utils.Bundle.get(Bundle.java:126)
        at com.watabou.utils.Bundle.get(Bundle.java:138)
        at com.shatteredpixel.shatteredpixeldungeon.Rankings.loadGameData(Rankings.java:188)
        at com.shatteredpixel.shatteredpixeldungeon.windows.WndRanking$1.run(WndRanking.java:70)

**Comment by 00-Evan** [comment]
What version of the game are you playing? Those line numbers do not match up to the latest release.

**Comment by teddytree** [comment]
Sorry, this was meant for shattered-pixel-dungeon-gdx. The version is v0.5.0b.

**Comment by 00-Evan** [comment]
the gdx build has a separate repo: https://github.com/00-Evan/shattered-pixel-dungeon-gdx
