### ISSUE TITLE
java.lang.NullPointerException: Cannot assign field "visible" because "this.burning" is null

### ISSUE THREAD

**Issue by Anonymous3-a** [00-Evan/shattered-pixel-dungeon#1914]
I was throwing potions at the wood barrier to burn it down. The first one wasn't a fire potion, but the second evidently was, because when I threw it, I got a
```
[GAME] java.lang.NullPointerException: Cannot assign field "visible" because "this.burning" is null
	at com.shatteredpixel.shatteredpixeldungeon.sprites.CharSprite.update(CharSprite.java:529)
	at com.shatteredpixel.shatteredpixeldungeon.sprites.HeroSprite.update(HeroSprite.java:161)
	at com.watabou.noosa.Group.update(Group.java:66)
	at com.watabou.noosa.Group.update(Group.java:66)
	at com.watabou.noosa.Scene.update(Scene.java:63)
	at com.shatteredpixel.shatteredpixeldungeon.scenes.PixelScene.update(PixelScene.java:203)
	at com.shatteredpixel.shatteredpixeldungeon.scenes.GameScene.update(GameScene.java:729)
	at com.watabou.noosa.Game.update(Game.java:289)
	at com.watabou.noosa.Game.step(Game.java:252)
	at com.watabou.noosa.Game.render(Game.java:178)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:193)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:167)
	at com.shatteredpixel.shatteredpixeldungeon.desktop.DesktopLauncher.main(DesktopLauncher.java:189)
```

**Comment by Anonymous3-a** [comment]
The seed is NDH-YXP-HCM in case it's needed.

**Comment by 00-Evan** [comment]
This is a bug that I've gotten sporadic reports on for a little bit now (mainly from desktop users), It's rare and should just be a once-off, but I am already attempting a proper fix in the next update.

**Comment by Anonymous3-a** [comment]
Alright, thanks. Should this issue be closed now?

**Comment by 00-Evan** [comment]
It should stay open to track the status of issue, as it becomes fixed in beta and then in the full release.
