### ISSUE TITLE
Linux desktop version crashes

### ISSUE THREAD

**Issue by Thimoteus** [00-Evan/shattered-pixel-dungeon#48]
I just updated to 0.3.0c on Arch Linux 64-bit, and it appears to crash on levels with traps. Here's the output:

```
Exception in thread "Thread-2" java.lang.NullPointerException
	at com.watabou.noosa.BitmapText.measure(BitmapText.java:174)
	at com.shatteredpixel.shatteredpixeldungeon.ui.UpdateNotification.layout(UpdateNotification.java:124)
	at com.shatteredpixel.shatteredpixeldungeon.ui.UpdateNotification.updateMessage(UpdateNotification.java:156)
	at com.shatteredpixel.shatteredpixeldungeon.ui.UpdateNotification.access$200(UpdateNotification.java:24)
	at com.shatteredpixel.shatteredpixeldungeon.ui.UpdateNotification$1.run(UpdateNotification.java:84)
Exception in thread "Thread-3" java.lang.NullPointerException
	at com.watabou.noosa.BitmapText.measure(BitmapText.java:174)
	at com.shatteredpixel.shatteredpixeldungeon.ui.UpdateNotification.layout(UpdateNotification.java:124)
	at com.shatteredpixel.shatteredpixeldungeon.ui.UpdateNotification.updateMessage(UpdateNotification.java:156)
	at com.shatteredpixel.shatteredpixeldungeon.ui.UpdateNotification.access$200(UpdateNotification.java:24)
	at com.shatteredpixel.shatteredpixeldungeon.ui.UpdateNotification$1.run(UpdateNotification.java:84)
Exception in thread "Thread-1" java.lang.NullPointerException
	at com.watabou.noosa.BitmapText.measure(BitmapText.java:174)
	at com.shatteredpixel.shatteredpixeldungeon.ui.UpdateNotification.layout(UpdateNotification.java:124)
	at com.shatteredpixel.shatteredpixeldungeon.ui.UpdateNotification.updateMessage(UpdateNotification.java:156)
	at com.shatteredpixel.shatteredpixeldungeon.ui.UpdateNotification.access$200(UpdateNotification.java:24)
	at com.shatteredpixel.shatteredpixeldungeon.ui.UpdateNotification$1.run(UpdateNotification.java:84)
com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: traps.png
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:140)
	at com.badlogic.gdx.graphics.glutils.FileTextureData.prepare(FileTextureData.java:64)
	at com.badlogic.gdx.graphics.Texture.load(Texture.java:130)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:121)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:100)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:92)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:88)
	at com.watabou.gdx.GdxTexture.<init>(GdxTexture.java:10)
	at com.watabou.gltextures.TextureCache.getBitmap(TextureCache.java:100)
	at com.watabou.gltextures.TextureCache.get(TextureCache.java:68)
	at com.watabou.noosa.Image.texture(Image.java:64)
	at com.watabou.noosa.Image.<init>(Image.java:55)
	at com.shatteredpixel.shatteredpixeldungeon.sprites.TrapSprite.<init>(TrapSprite.java:18)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:379)
	at com.badlogic.gdx.utils.reflect.ClassReflection.newInstance(ClassReflection.java:63)
	at com.watabou.noosa.Group.recycle(Group.java:158)
	at com.shatteredpixel.shatteredpixeldungeon.scenes.GameScene.addTrapSprite(GameScene.java:478)
	at com.shatteredpixel.shatteredpixeldungeon.scenes.GameScene.create(GameScene.java:173)
	at com.watabou.noosa.Game.switchScene(Game.java:222)
	at com.watabou.noosa.Game.step(Game.java:201)
	at com.watabou.noosa.Game.render(Game.java:137)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:207)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:114)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found: traps.png (Internal)
	at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:136)
	at com.badlogic.gdx.files.FileHandle.readBytes(FileHandle.java:222)
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:137)
	... 26 more
java.lang.NullPointerException
	at com.watabou.gltextures.SmartTexture.<init>(SmartTexture.java:47)
	at com.watabou.gltextures.SmartTexture.<init>(SmartTexture.java:41)
	at com.watabou.gltextures.TextureCache.get(TextureCache.java:68)
	at com.watabou.noosa.Image.texture(Image.java:64)
	at com.watabou.noosa.Image.<init>(Image.java:55)
	at com.shatteredpixel.shatteredpixeldungeon.sprites.TrapSprite.<init>(TrapSprite.java:18)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:379)
	at com.badlogic.gdx.utils.reflect.ClassReflection.newInstance(ClassReflection.java:63)
	at com.watabou.noosa.Group.recycle(Group.java:158)
	at com.shatteredpixel.shatteredpixeldungeon.scenes.GameScene.addTrapSprite(GameScene.java:478)
	at com.shatteredpixel.shatteredpixeldungeon.scenes.GameScene.create(GameScene.java:173)
	at com.watabou.noosa.Game.switchScene(Game.java:222)
	at com.watabou.noosa.Game.step(Game.java:201)
	at com.watabou.noosa.Game.render(Game.java:137)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:207)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:114)
Exception in thread "LWJGL Application" java.lang.NullPointerException
	at com.shatteredpixel.shatteredpixeldungeon.scenes.GameScene.addTrapSprite(GameScene.java:478)
	at com.shatteredpixel.shatteredpixeldungeon.scenes.GameScene.create(GameScene.java:173)
	at com.watabou.noosa.Game.switchScene(Game.java:222)
	at com.watabou.noosa.Game.step(Game.java:201)
	at com.watabou.noosa.Game.render(Game.java:137)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:207)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:114)
```

I'm guessing it can't find `traps.png`?

**Comment by 00-Evan** [comment]
the GDX build has its own repo, please post any issues there and i'll be happy to look into them.
https://github.com/00-Evan/shattered-pixel-dungeon-gdx/issues

**Comment by 00-Evan** [comment]
made my own, will address this issue shortly.
