### ISSUE TITLE
Latest beta crashes on start-up.

### ISSUE THREAD

**Issue by Scupake** [00-Evan/shattered-pixel-dungeon#766]
No idea what is causing this, I have Android 4.4.2 and my device is SM-T230.

**Comment by 00-Evan** [comment]
I'll need information about the crash itself, such as logcat output.

**Comment by praecipitator** [comment]
I have that, too. Tried to post it before, but github refused to work. OnePlus5T, Android 11, LineageOS.

As for logcat, it took me a while, but I think this might be the relevant part:
```
08-10 23:01:16.103  1450  1762 I ActivityManager: Start proc 29880:com.shatteredpixel.shatteredpixeldungeon/u0a317 for pre-top-activity {com.shatteredpixel.shatteredpixeldungeon/com.shatteredpixel.shatteredpixeldungeon.android.AndroidLauncher}
08-10 23:01:16.124 29880 29880 E redpixeldungeo: Not starting debugger since process cannot load the jdwp agent.
08-10 23:01:16.148 29880 29880 D NetworkSecurityConfig: No Network Security Config specified, using platform default
08-10 23:01:16.162  1450  3007 I ActivityTaskManager: START u0 {cmp=com.shatteredpixel.shatteredpixeldungeon/.android.AndroidGame} from uid 10317
08-10 23:01:16.148 29880 29880 D NetworkSecurityConfig: No Network Security Config specified, using platform default
08-10 23:01:16.164   826   826 D android.hardware.power@1.3-service.oneplus_msm8998: LAUNCH ON
08-10 23:01:16.178  1450  4435 W ActivityTaskManager: Tried to set launchTime (0) < mLastActivityLaunchTime (10712564)
08-10 23:01:16.190 29880 29880 D AndroidRuntime: Shutting down VM
08-10 23:01:16.191 29880 29880 E AndroidRuntime: FATAL EXCEPTION: main
08-10 23:01:16.191 29880 29880 E AndroidRuntime: Process: com.shatteredpixel.shatteredpixeldungeon, PID: 29880
08-10 23:01:16.191 29880 29880 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.shatteredpixel.shatteredpixeldungeon/com.shatteredpixel.shatteredpixeldungeon.android.AndroidGame}: java.lang.NullPointerException: Attempt to invoke interface method 'a.c$a a.c.getType()' on a null object reference
08-10 23:01:16.191 29880 29880 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
08-10 23:01:16.191 29880 29880 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
08-10 23:01:16.191 29880 29880 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
08-10 23:01:16.191 29880 29880 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
08-10 23:01:16.191 29880 29880 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
08-10 23:01:16.191 29880 29880 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
08-10 23:01:16.191 29880 29880 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-10 23:01:16.191 29880 29880 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
08-10 23:01:16.191 29880 29880 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
08-10 23:01:16.191 29880 29880 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-10 23:01:16.191 29880 29880 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
08-10 23:01:16.191 29880 29880 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
08-10 23:01:16.191 29880 29880 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'a.c$a a.c.getType()' on a null object reference
08-10 23:01:16.191 29880 29880 E AndroidRuntime: 	at com.watabou.utils.DeviceCompat.legacyDevice(DeviceCompat.java:1)
08-10 23:01:16.191 29880 29880 E AndroidRuntime: 	at com.shatteredpixel.shatteredpixeldungeon.android.AndroidGame.onCreate(AndroidGame.java:19)
08-10 23:01:16.191 29880 29880 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7994)
08-10 23:01:16.191 29880 29880 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7978)
08-10 23:01:16.191 29880 29880 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
08-10 23:01:16.191 29880 29880 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
08-10 23:01:16.191 29880 29880 E AndroidRuntime: 	... 11 more
08-10 23:01:16.194  1450 29905 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
08-10 23:01:16.194  1450  3007 W ActivityTaskManager:   Force finishing activity com.shatteredpixel.shatteredpixeldungeon/.android.AndroidGame
08-10 23:01:16.203  1450  1761 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
08-10 23:01:16.204  1450  1761 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
08-10 23:01:16.207 29880 29880 I Process : Sending signal. PID: 29880 SIG: 9
08-10 23:01:16.220  1450 11933 I ActivityManager: Process com.shatteredpixel.shatteredpixeldungeon (pid 29880) has died: prcp TOP 
08-10 23:01:16.220  1450  1763 I libprocessgroup: Successfully killed process cgroup uid 10317 pid 29880 in 0ms
08-10 23:01:16.221   804   804 I Zygote  : Process 29880 exited due to signal 9 (Killed)
08-10 23:01:16.242   826   826 D android.hardware.power@1.3-service.oneplus_msm8998: LAUNCH OFF
08-10 23:01:16.695  1450  1707 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{89238d4 u0 com.shatteredpixel.shatteredpixeldungeon/.android.AndroidGame t-1 f}}
```

**Comment by 00-Evan** [comment]
fixed in BETA-2
