### ISSUE TITLE
Error updating on Arch Linux

### ISSUE THREAD

**Issue by japhir** [00-Evan/shattered-pixel-dungeon#884]
Hi! For me the shattered-pd installer on arch, from [this AUR package](https://aur.archlinux.org/packages/shattered-pixel-dungeon-git/) fails with the below errors. I hope this is useful!

```
==> Making package: shattered-pixel-dungeon-git 5006v1.0.3-1 (Wed 15 Dec 2021 10:39:29 AM CET)
==> Retrieving sources...
  -> Updating shattered-pixel-dungeon git repo...
Fetching origin
  -> Found shattered-pixel-dungeon.sh
  -> Found shattered-pixel-dungeon.desktop
==> Validating source files with sha512sums...
    shattered-pixel-dungeon ... Skipped
    shattered-pixel-dungeon.sh ... Passed
    shattered-pixel-dungeon.desktop ... Passed
==> Making package: shattered-pixel-dungeon-git 5006v1.0.3-1 (Wed 15 Dec 2021 10:39:30 AM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating shattered-pixel-dungeon git repo...
Fetching origin
  -> Found shattered-pixel-dungeon.sh
  -> Found shattered-pixel-dungeon.desktop
==> Validating source files with sha512sums...
    shattered-pixel-dungeon ... Skipped
    shattered-pixel-dungeon.sh ... Passed
    shattered-pixel-dungeon.desktop ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of shattered-pixel-dungeon git repo...
Cloning into 'shattered-pixel-dungeon'...
done.
==> Starting prepare()...
==> Starting pkgver()...
==> Updated version: shattered-pixel-dungeon-git 5137v1.1.0-1
==> Sources are ready.
shattered-pixel-dungeon-git-5006v1.0.3-1: parsing pkg list...
==> Making package: shattered-pixel-dungeon-git 5137v1.1.0-1 (Wed 15 Dec 2021 10:39:34 AM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Starting build()...
Downloading https://services.gradle.org/distributions/gradle-7.2-all.zip
..............10%...............20%...............30%...............40%...............50%...............60%...............70%...............80%...............90%...............100%

Welcome to Gradle 7.2!

Here are the highlights of this release:
 - Toolchain support for Scala
 - More cache hits when Java source files have platform-specific line endings
 - More resilient remote HTTP build cache behavior

For more details see https://docs.gradle.org/7.2/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)
Could not write standard input to Gradle build daemon.
java.io.IOException: Stream closed
        at java.base/java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:445)
        at java.base/java.io.OutputStream.write(OutputStream.java:162)
        at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
        at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
        at org.gradle.process.internal.streams.ExecOutputHandleRunner.forwardContent(ExecOutputHandleRunner.java:68)
        at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:53)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
        at java.base/java.lang.Thread.run(Thread.java:833)

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/7.2/userguide/gradle_daemon.html
Process command line: /usr/lib/jvm/java-17-openjdk/bin/java -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.base/java.nio.charset=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.util.concurrent.atomic=ALL-UNNAMED -Xmx2048m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /tmp/makepkg/shattered-pixel-dungeon-git/src/wrapper/dists/gradle-7.2-all/260hg96vuh6ex27h9vo47iv4d/gradle-7.2/lib/gradle-launcher-7.2.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 7.2
Please read the following process output to find out more:
-----------------------
Unrecognized VM option 'MaxPermSize=512m'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'shattered-pixel-dungeon-git-5006v1.0.3-1':
error: packages failed to build: shattered-pixel-dungeon-git-5006v1.0.3-1
```

**Comment by 00-Evan** [comment]
Sorry, but I don't provide support for unofficial distributions of the game. It looks like a VM option they added might be causing the issue.

**Comment by japhir** [comment]
Fair enough! Thanks for your nice game :)

**Comment by prurigro** [comment]
Hey, the VM option seems to be getting set here: https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/gradle.properties#L7 -- patching it out before building fixes the package.

Cheers!
