### ISSUE TITLE
Crash with Patreon Desktop UI preview jar

### ISSUE THREAD

**Issue by SomeTroglodyte** [00-Evan/shattered-pixel-dungeon#908]
Ran ShatteredPD-v1.2.2-PATREON-PREVIEW.jar down to the first shop. Clicking on a buyable scroll 2 tiles away crashed. Cloned '1.1.2-indev' and ran save (which indeed showed a state just before said crash) in AS debugger, same click, no crash.

<details><summary>console output</summary>

[GAME] You defeated skeleton.
[GAME] java.lang.RuntimeException: Text measured from the actor thread!
	at com.watabou.noosa.RenderedText.measure(RenderedText.java:80)
	at com.watabou.noosa.RenderedText.<init>(RenderedText.java:59)
	at com.shatteredpixel.shatteredpixeldungeon.ui.RenderedTextBlock.build(RenderedTextBlock.java:125)
	at com.shatteredpixel.shatteredpixeldungeon.ui.RenderedTextBlock.text(RenderedTextBlock.java:72)
	at com.shatteredpixel.shatteredpixeldungeon.ui.InventoryPane.updateInventory(InventoryPane.java:304)
	at com.shatteredpixel.shatteredpixeldungeon.ui.InventoryPane.refresh(InventoryPane.java:251)
	at com.shatteredpixel.shatteredpixeldungeon.items.Item.updateQuickslot(Item.java:494)
	at com.shatteredpixel.shatteredpixeldungeon.items.artifacts.UnstableSpellbook$bookRecharge.act(UnstableSpellbook.java:299)
	at com.shatteredpixel.shatteredpixeldungeon.actors.Actor.process(Actor.java:274)
	at com.shatteredpixel.shatteredpixeldungeon.scenes.GameScene$2.run(GameScene.java:688)
</details>

Since desktop saves much more often than 'droid, this already overwrote the state, so, sorry, can't check whether the jar would have repro'ed the crash. Feel free to close unanswered, I'm just offering food for thought.

**Comment by 00-Evan** [comment]
This is not the place to report issues with preview builds of the game as they have no associated source release or general availability. Please DM me on Patreon or Discord, or email me.

**Comment by 00-Evan** [comment]
I've now resolved this issue, working on one or two other small adjustments and will have another Patreon preview out in an hour or two.
